spring:
  application:
    name: record-memories
  servlet:
    multipart:
      max-request-size: 5242880
      max-file-size: 5242880
  redis:
    host: czed.top
    password: Chunzhen4.
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
    timeout: 10000
    database: 0
  datasource:
    url: jdbc:mysql://czed.top:3306/memories-dev?serverTimezone=GMT%2B8&characterEncoding=utf8&useUnicode=true
    username: root
    password: Chunzhen4.
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      # 下面为连接池的补充设置,应用到上面所有数据源中
      # 初始化大小,最小,最大
      initial-size: 5
      min-idle: 5
      max-active: 20
      # 配置获取连接等待超时的时间
      max-wait: 60000
      # 配置间隔多久才进行一次检测,检测需要关闭的空闲连接,单位是毫秒
      time-between-eviction-runs-millis: 600000
      # 配置一个连接在池中最小生存的时间,单位是毫秒
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat,wall
      use-global-data-source-stat: true
      connect-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      # 配置监控服务器
      stat-view-servlet:
        login-username: superadmin
        login-password: Chunzhen4.
        reset-enable: false
        url-pattern: /druid/*
        # 添加IP白名单
        #allow:
        # 添加IP黑名单,黑名单优先级更高
        #deny:
      web-stat-filter:
        # 添加过滤规则
        url-pattern: /*
        # 忽略过滤格式
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"

server:
  port: 8444

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

paths:
  resource:
    # 映射路径
    location: file:/D:/images/memories/
  memory:
    # 照片在服务器的存储路径
    location: D:/images/memories
  host:
    # 后端域名端口
    back: http://localhost:8444
